name: Documentation Compliance Check

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  docs-compliance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check documentation organization
        run: npm run check-docs

      - name: Run code quality checks
        run: npm run standards

      - name: Comment on PR (if violations found)
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 📋 Documentation Compliance Check Failed

              The documentation organization rule check failed. Please ensure all documentation is properly organized in the \`docs/\` folder.

              ### Required Structure:
              - \`docs/technical/\` - Development guidelines, technical specifications
              - \`docs/project/\` - Project plans, roadmaps, summaries
              - \`docs/ux-ui/\` - Design guidelines, UI/UX specifications
              - \`docs/copywriting/\` - Content guidelines, brand voice
              - \`docs/brand/\` - Brand identity, visual guidelines
              - \`docs/assets/\` - Asset management, media guidelines

              ### To fix:
              1. Run \`npm run check-docs\` locally to see violations
              2. Move documentation files to appropriate \`docs/\` subfolder
              3. Update any references to moved files
              4. Commit the changes

              For more information, see [docs/README.md](docs/README.md)`
            })
